### ISSUE TITLE
Postgis support

### ISSUE THREAD

**Issue by browniebroke** [tbicr/django-pg-zero-downtime-migrations#10]
I wanted to give this library a try on our project, but it immediately broke our tests as we use PostGIS. I haven't tried anything yet, but we could probably solve this through inheritance in our project.

Would it be a welcome contribution here or would you rather keep this separate? Maybe we could split the main functionality through a Mixin, which would help reuse. 

I'm not super familiar with DB backends internal, so please let me know if this doesn't sound feasible or if you see a better solution. Otherwise, I can try putting something together...

**Comment by tbicr** [comment]
Hi @browniebroke 

It can be a good idea to solve it in this project as django support postgis.

It welcomed to contribute there, but it also can be split through a Mixin if it really has sense.

I can help you with django backend knowleges. I'm not too familiar with django postgis integration, so you can provide some interesting examples if they are more useful than I can find in documentation.

**Comment by tbicr** [comment]
Hi, I prepared basic postgis backend support https://github.com/tbicr/django-pg-zero-downtime-migrations/pull/11, please check it out.

**Comment by browniebroke** [comment]
Awesome, that was fast! Will give a try. Thanks!
