### ISSUE TITLE
Publish release to pypi?

### ISSUE THREAD

**Issue by tony** [tbicr/django-pg-zero-downtime-migrations#30]
Will we have a release to pypi soon?

It could be a 0.10.1 to incorporate the latest fix #27 and maybe a 0.11 for django 3.2 and 4.0?

Relevant updates from [3.2](https://docs.djangoproject.com/en/dev/releases/3.2/) and [4.0](https://docs.djangoproject.com/en/dev/releases/4.0/):
- [postgresql/schema.py](https://github.com/django/django/commits/4.0/django/db/backends/postgresql/schema.py): starting at [`8c7992f`](https://github.com/django/django/commit/8c7992f658e1125f8dc20b19206e8bbbe4187372#diff-e3fea5d09fbc3286aafc3ed3ea77299b7649528754f410afa725045a8d2f74af), wider search [postgresql/](https://github.com/django/django/commits/4.0/django/db/backends/postgresql)
-  [base/schema.py](https://github.com/django/django/commits/4.0/django/db/backends/base/schema.py) starting at [`8c7992f`](https://github.com/django/django/commit/8c7992f658e1125f8dc20b19206e8bbbe4187372#diff-f7637259acc1ecbb74910a7df2879cae5f3209d7a87ab0ad06dbd594b27f1831)

**Comment by tbicr** [comment]
Published

**Comment by tony** [comment]
@tbicr Thank you! this works perfect
