### ISSUE TITLE
Do you have a workflow for running `prettier` on markdown files?

### ISSUE THREAD

**Issue by tony** [tbicr/django-pg-zero-downtime-migrations#35]
Have you ever hooked [prettier](https://github.com/prettier/prettier) into your editor before for markdown files? It automatically handles wrapping lines and tables.

https://github.com/tbicr/django-pg-zero-downtime-migrations/compare/master...tony:format-with-prettier

One command: `npx prettier --no-config --write README.md`

<details>

- `npx`: Run `npm` package CLI command without installing to system
- `--no-config`: Disregard any configs in user's dirs
- `--write`: save
- `README.md` ...: Files to format

</details>

![image](https://user-images.githubusercontent.com/26336/156863351-e614060b-ee6c-40bb-9dcf-3ffc2a6b116e.png)
</details>

**Comment by tbicr** [comment]
> Have you ever hooked [prettier](https://github.com/prettier/prettier) into your editor before for markdown files?

No before, I like table formating, for line wrapping not sure it is the best option if you want to edit text, otherwise, your editor should support similar logic or prettier should be integrated to pre-commit or check.

**Comment by tony** [comment]
@tbicr 

Would you like either of these?

1. a PR of https://github.com/tbicr/django-pg-zero-downtime-migrations/compare/master...tony:format-with-prettier, and / or
2. setup pre-commit config ([docs](https://prettier.io/docs/en/precommit.html#option-3-pre-commithttpsgithubcompre-commitpre-commit))

   `.pre-commit-config.yaml`

  ```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  ```

**Comment by tbicr** [comment]
@tony , both looks good, thank you

**Comment by tony** [comment]
@tbicr 

- #36: format README
- #37: `.pre-commit-config.yaml`

**Comment by tony** [comment]
@tbicr As a next step, i'm not sure if you have yet, but you need to configure https://pre-commit.ci/ bot with the repository by logging in

**Comment by tbicr** [comment]
@tony , can github action used instead https://github.com/pre-commit/action ?

**Comment by tony** [comment]
@tbicr 

Maybe but it looks like the author is moving away from the action

> DEPRECATED this action is in maintenance-only mode and will not be accepting new features.

>
> Please switch to using [pre-commit.ci](https://pre-commit.ci/) which is faster and has more features.

From the looks of it it's unsafe, re https://github.com/pre-commit/action/issues/148 and the bottom of the README

> while you could technically configure this for a public repository (using a personal access token), I can't think of a way to do this safely without exposing a privileged token to pull requests -- if you have any ideas, please leave an issue!

It may be fine to use https://pre-commit.ci/, if not we can simply not use the tool for now
