### ISSUE TITLE
Flag for deeming CREATE INDEX operation unsafe

### ISSUE THREAD

**Issue by korjak** [tbicr/django-pg-zero-downtime-migrations#44]
Currently when CREATE INDEX operation is detected, it is quietly replaced with CREATE INDEX CONCURRENTLY. It would be super useful to have a flag in settings, which would allow to choose whether the user wants backend to do that or just to consider this operation unsafe and possibly raise an exception (if an appropriate flag is set).

**Comment by tbicr** [comment]
Can you detailly describe your case? Because this lib doing a lot of standard django queries replacement to safe one https://github.com/tbicr/django-pg-zero-downtime-migrations/blob/master/django_zero_downtime_migrations/backends/postgres/schema.py#L176-L248 - there are `indexes` and `unique` (create index concurrently too), `fk` (require index creating concurrently to speedup fk checks), `check`, `not null` constraints.

Potentially you can override https://github.com/tbicr/django-pg-zero-downtime-migrations/blob/master/django_zero_downtime_migrations/backends/postgres/schema.py#L349-L363 to add logic you describe.

**Comment by korjak** [comment]
In the places you indicated, I'd like to introduce a flag for choosing whether the query should be replaced with a safe one or an exception should be raised. Can I just clone the repo, create a branch and prepare a PR with changes or I need some permissions to be granted first?

**Comment by tbicr** [comment]
I not sure I understood problem you want to solve completely so it hard to suggest best option there.

As I mentioned in https://github.com/tbicr/django-pg-zero-downtime-migrations/issues/44#issuecomment-1320419586 there are a few places where query replaced with safe variant (and index created too internally) so it would be nice to have vision how they should be handled too.

**Comment by korjak** [comment]
Ideally, I'd like to have flag RAISE_INSTEAD_REPLACEMENT, which would work in the following way:
- if set to False: everything works the current way
- if set to True: no query replacements take place. Instead, appropriate exceptions are raised. 

Basically, I'd like to be able to disable the lib's ability to replace django queries considered dangerous.

**Comment by korjak** [comment]
@tbicr how can I contribute those changes?

**Comment by tbicr** [comment]
it looks quite complicated to cover all cases library do standard query replacing or not, that also can be related to django version or settings. I think about different approach to check real sql, like [`sqlmigrate`](https://docs.djangoproject.com/en/4.1/ref/django-admin/#sqlmigrate) and get result using real sql for standard django and this lib comparison, but I don't dig it yet.

**Comment by tbicr** [comment]
there are some examples running `sqlmigrate` for tests `INSTALLED_APPS += ['tests.apps.good_flow_app']`

`DB_ENGINE=django.db.backends.postgresql`:

```
% DJANGO_SETTINGS_MODULE=tests.settings venv/bin/python manage.py sqlmigrate good_flow_app 0004
System check identified some issues:

WARNINGS:
good_flow_app.RelatedTestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
good_flow_app.TestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Alter field field on testtable
--
UPDATE "good_flow_app_testtable" SET "field" = 0 WHERE "field" IS NULL; SET CONSTRAINTS ALL IMMEDIATE;
ALTER TABLE "good_flow_app_testtable" ALTER COLUMN "field" SET NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
```

`DB_ENGINE=django_zero_downtime_migrations.backends.postgres`: 

```
% DJANGO_SETTINGS_MODULE=tests.settings venv/bin/python manage.py sqlmigrate good_flow_app 0004
System check identified some issues:

WARNINGS:
good_flow_app.RelatedTestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
good_flow_app.TestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Alter field field on testtable
--
UPDATE "good_flow_app_testtable" SET "field" = 0 WHERE "field" IS NULL; SET CONSTRAINTS ALL IMMEDIATE;
ALTER TABLE "good_flow_app_testtable" ADD CONSTRAINT "good_flow_app_testtable_field_c3f3a507_notnull" CHECK ("field" IS NOT NULL) NOT VALID;
ALTER TABLE "good_flow_app_testtable" VALIDATE CONSTRAINT "good_flow_app_testtable_field_c3f3a507_notnull";
ALTER TABLE "good_flow_app_testtable" ALTER COLUMN "field" SET NOT NULL;
ALTER TABLE "good_flow_app_testtable" DROP CONSTRAINT "good_flow_app_testtable_field_c3f3a507_notnull";
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
```

So looks it's better option to achieve you want with maximal coverage.

**Comment by tbicr** [comment]
same for index:

`DB_ENGINE=django.db.backends.postgresql`:

```
% DJANGO_SETTINGS_MODULE=tests.settings venv/bin/python manage.py sqlmigrate good_flow_app 0022
System check identified some issues:

WARNINGS:
good_flow_app.RelatedTestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
good_flow_app.TestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
BEGIN;
--
-- Create index test_index on field(s) test_field_int of model testtable
--
CREATE INDEX "test_index" ON "good_flow_app_testtable" ("test_field_int");
COMMIT;
```

`DB_ENGINE=django_zero_downtime_migrations.backends.postgres`:

```
% DJANGO_SETTINGS_MODULE=tests.settings venv/bin/python manage.py sqlmigrate good_flow_app 0022
System check identified some issues:

WARNINGS:
good_flow_app.RelatedTestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
good_flow_app.TestTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
BEGIN;
--
-- Create index test_index on field(s) test_field_int of model testtable
--
CREATE INDEX CONCURRENTLY "test_index" ON "good_flow_app_testtable" ("test_field_int");
COMMIT;

```
