### ISSUE TITLE
Using django-pg-zero-downtime-migrations our table is locked

### ISSUE THREAD

**Issue by goinnn** [tbicr/django-pg-zero-downtime-migrations#8]
Hi,

Thanks for your project! 

We think we have same problem. We have a model (MyModel) with 1.000.000 of rows. And we add a field with default value we have a lock during 30-120 seconds. Something like this: 

``` 
class MyModel(models.Model):
        ...
        # Adding a new field
        x = models.CharField(max_length=250, blank=True, default='XX')
        ...
```

And its migration:

``` 
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='x',
            field=models.CharField(blank=True, default='XX', max_length=250),
        ),
    ]
``` 

We have done a lot of tests, e.g.: we have created fields without default, but really default is "", and we get the same problem.

Currently, it is our workaround:

1. We create every field with null=True and default=None. So PostgreSQL don't have to write in every row anything.
2. We migrate via a django command every row of "MyModel". 
3. We update code, and remove null=False and adding default="XXX"
4. We update the code in production enviroment
5. We migrate via a django command every *new* row of "MyModel". 
6. We generate new migration to add "not null" constrain
7. We run last migration (6 point)

When we find your solution we were very happy, our workaround is very tricky, but your solutions does not work for us. We get a little more time locked (35-125 seconds) instead of get zero downtime.

It is our settings:

``` 
DATABASES = {
    'default': {
        'ENGINE': 'django_zero_downtime_migrations_postgres_backend',
        #'ENGINE': 'django.contrib.gis.db.backends.postgis',
        ...
    }
}

ZERO_DOWNTIME_MIGRATIONS_RAISE_FOR_UNSAFE = True

ZERO_DOWNTIME_MIGRATIONS_USE_NOT_NULL = False

``` 

Please, could you tell us what is wrong in our case?
Please, could you upload a little project example?

Thanks another time,

**Comment by goinnn** [comment]
We have just known if we add our new field with null=True, migrate database, remove null=True and migrate database another time this works fine.

So, something like this:

1.  Add field with null = True

```
class MyModel(models.Model):
        ...
        # Adding a new field
        x = models.CharField(max_length=250, blank=True, null=True)
        ...
```
2. Create migration and migrate. **No locking table**
3. Remove null=True and adding default="XX"

```
class MyModel(models.Model):
        ...
        # Adding a new field
        x = models.CharField(max_length=250, blank=True, default="XX")
        ...
```
4. Create migration and migrate. **No locking table**

Please could help us to understand it?

**Comment by tbicr** [comment]
Hi, 

Really strange behavior, I expect with your config `ZERO_DOWNTIME_MIGRATIONS_RAISE_FOR_UNSAFE = True` for trying add column with default value migration will stop running wiht notification that it's a unsafe operation. I will take a look next few days.

Can you also share version of postgres, django and this library you use?

**Comment by goinnn** [comment]
Hi @tbicr 

No, there is not a warning. With a warning notification ("ADD COLUMN NOT NULL is unsafe operation") we had understood this behaviour. It is possible your library has a bug and it does not show the notification.

PosgreSQL version: 9.4
Django version: 2.0.13
django-pg-zero-downtime-migrations: last commit from master branch [0f5bc8e84caf44ff8b8a280aaf97da74770537c3]

Thanks another time!

We are waiting your answer,

**Comment by tbicr** [comment]
Hi, @goinnn 

I fixed issue in library for adding nullable field with default, now it will raise error for your config. Please take a look changes https://github.com/tbicr/django-pg-zero-downtime-migrations/blob/master/CHANGES.md#04

I also updated most safe settings usage https://github.com/tbicr/django-pg-zero-downtime-migrations#usage, for example `ZERO_DOWNTIME_MIGRATIONS_STATEMENT_TIMEOUT` option can avoid you issue that you got with 30-120 seconds downtime.

> Currently, it is our workaround:
> 
>     We create every field with null=True and default=None. So PostgreSQL don't have to write in every row anything.
>     We migrate via a django command every row of "MyModel".
>     We update code, and remove null=False and adding default="XXX"
>     We update the code in production enviroment
>     We migrate via a django command every new row of "MyModel".
>     We generate new migration to add "not null" constrain
>     We run last migration (6 point) 

It's a pretty good way how to migration should be applied and this library should help you as possible.

I just want to get you attention to `not null` (not `CHECK field IS NOT NULL`) constraint that can also be reason of downtime: https://github.com/tbicr/django-pg-zero-downtime-migrations#dealing-with-not-null-constraint

> 1. Add field with null = True
> 
> ```
> class MyModel(models.Model):
>         ...
>         # Adding a new field
>         x = models.CharField(max_length=250, blank=True, null=True)
>         ...
> ```
> 
>  2. Create migration and migrate. **No locking table**
> 
>  3. Remove null=True and adding default="XX"
> 
> 
> ```
> class MyModel(models.Model):
>         ...
>         # Adding a new field
>         x = models.CharField(max_length=250, blank=True, default="XX")
>         ...
> ```
> 
> 4. Create migration and migrate. **No locking table**

There are can be issue on step 4 between migration applying and code updating when old code try to create records with already migrated schema that forbid `NULL` values.

I just describe my experience for this kind of migrations:

1. add new field `x = models.CharField(max_length=250, blank=True, null=True)`
2. create migration
3. alter field `x = models.CharField(max_length=250, blank=True, null=True, default="XX")`
4. create migration - there are will be defaults only for new records
5. apply migration on your env
6. apply new code on your env - it's important to use default in your code for new records before not null will be applied
7. add data migration to set default in case if `x IS NULL`
8. remove null=True `x = models.CharField(max_length=250, blank=True, default="XX")`
9. apply migration on you env
10. apply new code on your env

Feel free to reopen issue if you left any question about your migration.
